### ISSUE TITLE
Advanced Search: Einzelne Ticketfelder durchsuchbar machen

### ISSUE THREAD

**Issue by DustdevDM** [youji-dev/youji#67]
In der Ticketübersicht soll es die Möglichkeit geben nicht nur allgemein mithilfe eines Suchbegriffs alle Properties eines Tickets zu durchsuchen, sondern gezielt jede Property einzeln und gleichzeitig durchsuchbar zu machen. 

## Backend

[Aktuell](https://github.com/youji-dev/youji/blob/d0a029381ba3ee5b52083d69b6d473cfdc7a378f/backend/WebApi/Controllers/TicketController.cs#L61-L73) kann man nur einen einzelnen Suchbegriff eingeben, welcher dann mithilfe vieler logischer ODER Operatoren auf fast alle Properties mit `.Contains()` der Ticket Repository angewendet wird.

Stattdessen sollte ein neuer Endpunkt geschaffen werden, welcher über Query Parameter die Suche der meisten Properties ermöglicht. 

#### Durchsuchbare Properties:
- Title (Contains)
- Description (Contains)
- Priority (ID der Propertie)
- Author (Username)
- State (ID des State)
- Building (ID des Buildings)
- Room (Contains)
- Object (Contains)

## Frontend
Im Standard wird in der TicketListe nur ein Textfeld für das durchsuchen des Titels angezeigt. Dies soll erweitert werden. Es sollte möglichsein mithilfe eines Buttons, Switch oder ähnlichem eine erweiterte Form der Suche anzuzeigen. In dieser werden dann weitere Textfelder oder Selects für alle weiteren durchsuchbaren Props angezeigt

## ToDo

- [ ] UI als Mockup erstellen

### Backend
- [ ] Neuen Endpunkt für gezielte Suche nach Properties im TicketController erstellen
- [ ] Durchsuchbare Properties: Title, Description, Priority, Author, State, Building, Room, Object
- [ ] Alten Suchendpunkt entfernen

### Frontend
- [ ] Erweiterte Suchoption (Button/Switch) hinzufügen
- [ ] Textfelder/Selects für alle durchsuchbaren Properties anzeigen
- [ ] Altes Reposiory ersetzten
- [ ] Sortierung fixen und an das Backend verknüpfen

### Vorgänger
- #16
