### ISSUE TITLE
Automatische Ticket-Lösch-Job Logik einfügen

### ISSUE THREAD

**Issue by DustdevDM** [youji-dev/youji#72]
Anforderung des Ticketsystem war es, dass Tickets welche sich im "done" oder "erledigt" state befinden, automatisch nach 6 Monaten gelöscht werden. Da unsere States nicht hardcodet sondern voll konfigurierbar sind, wird dies eine Aufgabe von größeren Umfang.

## Anpassungen an States selbst
States müssen erweitert werden. In states muss konfigurierbar werden, ob diese eine automatische Löschung der eigenen Tickets durchführen sollen und wann dies passieren soll. Diese neuen Werte müssen dann über die API beim POST und PUT manipulierbar sein.

## Anpassungen an Tickets
Bei Tickets muss getrackt werden, wann diese zuletzt den State zugewiesen bekommen haben. Diese Information ist wichtig um dann bei der Lösch Job Logik zu tracken, welche Tickets eines States über dem festgelegten Ablaufdatum liegen. Dieser Datumswert muss sich immer ändern, wenn das Ticket in einen anderen State gesetzt wird, Daher muss im PUT geprüft werden, ob der State manipuliert wurde oder nicht. Der Wert wird nicht von Client gesetzt oder gesehen. Daher sollte in der Entity der JSONIGNORE Parameter gesetzt werden. 
```mermaid
erDiagram
    State {
        Guid Id
        string Name
        string Color
        bool AutoPurge "new"
        int AutoPurgeMonths "nullable new"
    }

    Ticket {
        Guid Id
        string Title
        string Description "nullable"
        Priority Priority
        string Author
        DateTime CreationDate
        State State
        Date LastStateUpdate "new"
        Building Building "nullable"
        string Room "nullable"
        string Object "nullable"
    }

    Ticket }o--|| State : "gehört zu einem"
```

## Job Logik
Das Backend muss regelmäßg Prüfen, welche Tickets welcher States über dem purge datum sind. Dafür kann das [Quartz.NET Nuget Package](https://www.quartz-scheduler.net/) verwendet werden.

Mit Quartz können regelmäßig Jobs ausgeführt werden. jobs sind hierbei einfach Klassen mit einer Execute funktion. In der API Startup Funktion kann Quartz wiefolgt konfiguriert werden:
![Image](https://github.com/user-attachments/assets/73002a07-8ca1-4727-85e9-f063312f6422)

Der Jobs sollte Prüfen, ob States mit purge option aktiv sind. Alle LastStateUpdate mit dem Ablaufdatum des States prüfen und löschen wenn es nötig ist.

## Frontend
Veränderte API Controller sollten in dem Frontend Request/Return Type und in frontend repository funktionen übernommen werden

## TODO Zusammenfassung
- [x] **States erweitern:**
  - [x] Neue Felder `AutoPurge` (bool) und `AutoPurgeMonths` (int?, nullable) in der State-Entity hinzufügen.
  - [x] API anpassen, um diese Felder bei POST und PUT zu verarbeiten.
  - [x] Funktionalität im Frontend übernehmen (Types Ordner, Reposiory Ordner)

- [x] **Tickets erweitern:**
  - [x] Feld `LastStateUpdate` (Date) in der Ticket-Entity hinzufügen. (`[JsonIgnore]` verwenden)
  - [x] Sicherstellen, dass `LastStateUpdate` bei jeder State-Änderung aktualisiert wird (im PUT prüfen).

- [x] **Job Logik:**
  - [x] Quartz.NET integrieren, um regelmäßige Prüfungen auszuführen.
  - [x] Job erstellen, der:
    - [x] Alle States mit aktiver `AutoPurge`-Option identifiziert.
    - [x] Tickets dieser States mit `LastStateUpdate` über dem Ablaufdatum löscht.
