### ISSUE TITLE
Prioritäten sollen auch wie Status Farben haben

### ISSUE THREAD

**Issue by DustdevDM** [youji-dev/youji#78]
In einer anderen Präsentation gab es das Feedback von Hausmeister: Die Farbe der Priorität sollte auch der übersicht sichtbar sein.

Bei uns haben unsere Prioritäten aktuell keine Farben. Jedoch unsere Status. Die Implementation können wir davon einfach übernehmen.

## Backend
Es muss die Priority Entity erweitert werden:
```mermaid
erDiagram
    Priority {
        Guid Id PK
        int Value
        string Name
        string Color
    }
```
Zudem muss der Controller für die Priority um diesen Wert (PUT und POST) erweitert werden.

## Frontend
Im Frontend muss in den types sowie ggf. in den repositories die neue color prop hinzugefügt werden, Zudem muss diese in der Ticket Übersicht sowie in der Ticket Detailsansicht mit visualisiert werden. Dafür kann das `coloredSelect` von Emillio verwendet werden. Im rahmen dieses Tickets kann auch die selbst umgesetzte select Auswahl in der Detailansicht für die States mit der `coloredSelect` ausgetauscht werden

### ToDo
- [x] **Backend**
  - [x] Priority Entity um `Color`-Eigenschaft erweitern.
  - [x] Priority Controller für `PUT` und `POST` um die `Color`-Eigenschaft erweitern.
- [x] **Frontend**
  - [x] `Color`-Property in Types und Repositories hinzufügen.
  - [x] Farbe der Prioritäten in der Ticket-Übersicht und -Detailansicht visualisieren.
  - [x] `coloredSelect` von Emillio für Prioritäten-Auswahl verwenden.
  - [ ] ~Bestehende Select-Auswahl für States in der Detailansicht durch `coloredSelect` ersetzen.~ Nicht für die Verwendung von Formularen angedacht

## Vorgänger
- #16
